/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Astronaut.glb -o src/components/3d/Astronaut.tsx --types 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["0"]: THREE.Mesh;
    ["0_1"]: THREE.Mesh;
  };
  materials: {
    astnt1_1: THREE.MeshStandardMaterial;
    astnt1_2: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Astronaut.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes["0"].geometry} material={materials.astnt1_1} />
        <mesh geometry={nodes["0_1"].geometry} material={materials.astnt1_2} />
      </group>
    </group>
  );
}

useGLTF.preload("/Astronaut.glb");
